import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — EquipCheck",
  description: "EquipCheck terms of service. Read the terms governing use of our AI equipment validation platform.",
};

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-white">
      <header className="border-b border-slate-200 bg-[#0F172A]">
        <div className="mx-auto flex h-16 max-w-4xl items-center px-4 sm:px-6">
          <Link href="/" className="font-display text-xl font-bold text-white">
            EquipCheck
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-4xl px-4 py-16 sm:px-6">
        <h1 className="font-display text-3xl font-bold text-slate-900">Terms of Service</h1>
        <p className="mt-2 text-sm text-slate-500">Last updated: February 2026</p>

        <div className="prose prose-slate mt-10 max-w-none">
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing or using EquipCheck (&ldquo;the Service&rdquo;), you agree to be bound by these
            Terms of Service. If you do not agree to these terms, do not use the Service.
          </p>

          <h2>2. Description of Service</h2>
          <p>
            EquipCheck is an AI-powered equipment validation tool that compares equipment lists against
            master specifications to identify mismatches, missing items, and quantity discrepancies.
            The Service is provided as a software-as-a-service (SaaS) platform.
          </p>

          <h2>3. Account Registration</h2>
          <p>
            To access certain features, you must create an account. You are responsible for maintaining
            the confidentiality of your account credentials and for all activities that occur under your
            account. You must provide accurate and complete information when creating your account.
          </p>

          <h2>4. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul>
            <li>Use the Service for any unlawful purpose</li>
            <li>Attempt to gain unauthorized access to the Service or its systems</li>
            <li>Interfere with or disrupt the Service or its infrastructure</li>
            <li>Use automated tools to scrape or extract data from the Service beyond normal API usage</li>
            <li>Resell or redistribute the Service without written authorization</li>
            <li>Upload files containing malware or malicious content</li>
          </ul>

          <h2>5. Subscription Plans and Billing</h2>
          <ul>
            <li><strong>Free Plan:</strong> 3 validations per month at no charge</li>
            <li><strong>Professional Plan:</strong> $149/month for 75 validations per month</li>
            <li><strong>Business Plan:</strong> $299/month for unlimited validations</li>
          </ul>
          <p>
            Paid subscriptions are billed monthly through Stripe. You may cancel your subscription at
            any time through the billing portal. Cancellations take effect at the end of the current
            billing period. We do not offer prorated refunds for partial months.
          </p>

          <h2>6. AI-Generated Results &mdash; Disclaimer</h2>
          <p>
            <strong>
              EquipCheck&rsquo;s validation results are generated by artificial intelligence and are
              provided as a decision-support tool, not as a substitute for professional judgment.
            </strong>
          </p>
          <ul>
            <li>Results should be reviewed by qualified personnel before making purchasing or deployment decisions</li>
            <li>We do not guarantee 100% accuracy of validation results</li>
            <li>AI may misinterpret ambiguous item descriptions or non-standard naming conventions</li>
            <li>You are solely responsible for verifying results before acting on them</li>
          </ul>

          <h2>7. Intellectual Property</h2>
          <p>
            You retain all rights to your uploaded files and data. EquipCheck does not claim ownership
            of any content you upload. The Service, including its design, code, and branding, is the
            property of EquipCheck.
          </p>

          <h2>8. Data Handling</h2>
          <p>
            Your use of the Service is also governed by our{" "}
            <Link href="/privacy" className="text-blue-600 hover:text-blue-700">Privacy Policy</Link>.
            Uploaded equipment files are processed in memory and deleted immediately after validation.
            We do not retain your uploaded files.
          </p>

          <h2>9. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, EquipCheck shall not be liable for any indirect,
            incidental, special, consequential, or punitive damages, including but not limited to loss
            of profits, data, or business opportunities, arising from your use of the Service.
          </p>
          <p>
            Our total liability for any claim arising from the Service shall not exceed the amount you
            paid us in the 12 months preceding the claim.
          </p>

          <h2>10. Service Availability</h2>
          <p>
            We strive to maintain high availability but do not guarantee uninterrupted access to the
            Service. We may perform maintenance, updates, or modifications that temporarily affect
            availability. We will make reasonable efforts to notify users of planned downtime.
          </p>

          <h2>11. Termination</h2>
          <p>
            We reserve the right to suspend or terminate your account if you violate these Terms. You
            may delete your account at any time. Upon termination, your account data will be permanently
            deleted in accordance with our Privacy Policy.
          </p>

          <h2>12. Changes to Terms</h2>
          <p>
            We may update these Terms from time to time. Continued use of the Service after changes
            constitutes acceptance of the updated Terms. We will notify you of material changes via
            email or in-app notification.
          </p>

          <h2>13. Governing Law</h2>
          <p>
            These Terms shall be governed by and construed in accordance with applicable law, without
            regard to conflict of law principles.
          </p>

          <h2>14. Contact Us</h2>
          <p>
            If you have any questions about these Terms, please contact us at{" "}
            <a href="mailto:legal@equipcheck.io">legal@equipcheck.io</a>.
          </p>
        </div>
      </main>

      <footer className="border-t border-slate-200 bg-slate-50 px-4 py-8 sm:px-6">
        <div className="mx-auto max-w-4xl text-center">
          <Link href="/" className="text-sm text-slate-500 hover:text-slate-700">
            &larr; Back to EquipCheck
          </Link>
        </div>
      </footer>
    </div>
  );
}
